remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: D2R Speedrun Tool
description: Application that scans your Diablo 2 Resurrected saves and displays stats about the last updated one.
theme: jekyll-theme-cayman
google_analytics: G-73CHK4Y998
